name: Container Build


on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "20*"
    branches:
      - main
    paths:
      - "**/*.rs"
      - "addon/**"
      - "**/Cargo.*"
      - ".github/workflows/build.yml"
      - ".cargo/config.toml"
      - "scripts/build-cross.sh"
      - "scripts/build-docker.sh"
      - "Dockerfile"
      - ".dockerignore"


env:
  IMAGE: ghcr.io/homeassilol/govee2mqtt


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    permissions:
      contents: read
